### ISSUE TITLE
how to run 'visualize.py'?

### ISSUE THREAD

**Issue by malywood** [drasros/sleep_staging_shhs#4]
i use 'train.py', it worked sucessfully. but i fail to run 'visualize.py'. 

> NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key cnn10/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at D:\Anaconda3\envs\capstone\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

when i run 'visualize', there's error like that.

so what can i do to run  'visualize.py'?

**Comment by drasros** [comment]
Hi, 

Are you using the same (old) versions of all dependencies ?
If you are using a more recent version of Tensorflow for example, I wouldn't be surprised if some things have to be changed.. maybe have a look at this page: https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver and update the code..
also:
https://stackoverflow.com/questions/51032858/tf-train-saver-failing-to-restore-checkpoint-from-path

I don't have the resources to maintain this old code, sorry...

**Comment by malywood** [comment]
I made virtual env according to 'enviroment.yml' to run your code. So Is there any other reason?

**Comment by malywood** [comment]
Hi. i solved the problem. i didn't modify config of 'viz.py'. i train model for default config, but config of viz.py was different from default one. so  thank you so much. have nice day!

**Comment by drasros** [comment]
Thank you for writing back! Please don't hesitate to send a PR for the
right config if you want. Have a nice day too.
